# Generated by Django 4.0.2 on 2022-02-21 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 2, 33, 14, 834269, tzinfo=utc)),
        ),
    ]
