# Generated by Django 4.0.2 on 2022-02-21 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
